name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: [compile-assets, test-php]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Setup Enviroment
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0.10"
      - name: Install Packages
        run: composer install --no-dev
      - name: Set up env
        run: cp .env.example .env
      - name: Generate envirnment key
        run: php artisan key:generate
      - name: Run Migration
        run: php artisan migrate
      - name: Run Seed
        run: php artisan db:seed
      - name: Run tests
        run: vendor/bin/phpunit
      - uses: actions/checkout@v2
      - name: Download build assets
        uses: actions/download-artifact@v1
        with:
          name: assets
          path: public
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: "8.0.10"
          extensions: mbstring, bmath
      - name: Composer install
        run: composer install
      - name: Setup Deployer
        uses: atymic/deployer-php-action@master
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy to Prod
        run:
          dep deploy production --tag=${{ env.GITHUB_REF }} -vvv

        # -   name: Deploy to Server
        #     uses: ngocquyhoang/deploy@laravel
        #     with:
        #         user: user
        #         host: host
        #         port: port
        #         path: path
        #         owner: owner
        #     env:
        #         DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
